name: heroku_deploy
on:
  push:
    branches:
      - develop
      - enh/deploy-to-heroku

jobs:                        
    build:                          
    runs-on: ubuntu-latest                        
       steps:
           - uses: actions/checkout@v2        
           - uses: akhileshns/heroku-deploy@v3.6.8
           with: 
               heroku_api_key: ${{secrets.HEROKU_API_KEY}}  
               heroku_app_name: "grn-web"                                 
               heroku_email: ${{secrets.HEROKU_EMAIL}}                                   
               healthcheck: "https://grn-web.herokuapp.com/"                                     
               usedocker: true                                  
               delay: 60                                 
               rollbackonhealthcheckfailed: true
